### ISSUE TITLE
aggregation using topics API

### ISSUE THREAD

**Issue by kzhong130** [patcg-individual-drafts/topics#10]
Hi there, thanks for sharing this awesome proposal. I have one quick follow up questions regarding how to do aggregation using this API. 
In original floc proposal, each websites would be able to view the cohort id of a user. One benefit that I can think of is that the website can learn which group of users visited its site most frequently. With this aggregation data, the advertiser can adjust its bidding strategy for users from different group. 
For example, it could bid higher in the auction for user from a group that visited its site most frequently. 

In this API, is there any plan for making such aggregation above possible as well?
One option that I can think of is that the advertisers also fetch the `topics` when the browser visits its own website, and uses the `topics` as an identifier of that user instead of using the cohort id.

**Comment by jkarlin** [comment]
Yes, it's possible at the topic level as you say. That is, you could use the list of common topics of users that visit your site.
