### ISSUE TITLE
Proposed improvement to random noise

### ISSUE THREAD

**Issue by jkarlin** [patcg-individual-drafts/topics#121]
Two issues have been raised about the 5% random noise that Topics introduces.

1. Issue #73 points out that the signal-to-noise ratio of Topics is unequal across callers, depending on their third-party presence. A caller that has little third party presence will receive mostly noise while a caller with significant presence will receive mostly signal.

2. Issue #75 points out that it is trivial to determine if a returned topic is noise or not by calling the API from an origin that has not called the API at all, or at least not on many pages (e.g., such as from the top frame of a page). If something is returned, then it should either be the topic of the page itself, or it is random.

We can address #73 and significantly mitigate #75 with the following change: If the real topic is to be replaced with a random topic due to the 5% coin flip, then the caller will only receive the random topic if they would have received the real topic. That is, the caller had recently "witnessed" the real topic. This ensures that 5% of returned topics are random, no matter what the caller's reach is across sites. 

This proposal also makes it significantly more cumbersome to detect which topics are the random topics, as for instance the top frame site will only receive the random topic if the real topic of the week for the user matches the site's topic. It is still possible to suss out the random topic (e.g., crafting a site that only uses the API on sites with a known set of topics, and if a topic is returned that is not one of those topics then it is random) but this is no longer so trivial to perform.

*edited for clarity

**Comment by stguav** [comment]
Just for maintaining a consistent history, this is a reversal of the reasoning in https://github.com/patcg-individual-drafts/topics/issues/41#issuecomment-1058194712? (Perhaps should be merged with that thread??)

**Comment by stguav** [comment]
Ah, I see, re-reading more carefully it makes sense now, hopefully referencing the previous issue is still helpful.

**Comment by jkarlin** [comment]
We discussed this in the last [meeting](https://github.com/patcg-individual-drafts/topics/blob/main/meetings/2022-12-05-minutes.md). Folks were supportive. I'll put together a PR.
