### ISSUE TITLE
Reconciliation of usage -> topics realities

### ISSUE THREAD

**Issue by pbannist** [patcg-individual-drafts/topics#21]
As a component of the testing of the Topics system, some reconciliation should be done to ensure that each topic is of material size to be useful AND that there are enough domains/usage to qualify a large enough group of users. This would be above and beyond any privacy requirements. 

For example, there appear to be very few domains that could cleanly map to the "Blues Music" topic. If origin trials and other testing prove that fewer than 50,000 users might be qualified into that segment, it should be removed from the taxonomy. 

50,000 users might be enough to guarantee privacy, but is likely not enough to be useful from an advertising perspective. Since the number of segments is going to be low (in the hundreds, in theory), each one should be of maximal benefit from an advertising perspective, and very small segments will be of limited value overall. So in the example, Blues Music would be removed and replaced with another topic that might achieve higher scale.

**Comment by PanMat** [comment]
50,000 cutoff is a generalist opinion and there is no basis for it. For a law firm litigating mesothelioma, even 5,000 audiences are a gold mine.

**Comment by jkarlin** [comment]
There is a floor on the number of users in each topic due to the fact that 5% of the time a random topic is returned. So, given ~500 topics, that means that any given topic should be returned 1 in every 10,000 calls.
