### ISSUE TITLE
Aggregate Conversion Reporting

### ISSUE THREAD

**Issue by RussStringham** [patcg-individual-drafts/topics#23]
Assuming that an aggregate conversion reporting mechanism is also supported by the browser, when a user converts on an advertiser's site, for each ad viewed and/or clicked, the aggregation report should include the:
- the number of times each ad and/or campaign ID was viewed/clicked (not new to this proposal)
- the topics that were shared on each site where an ad was displayed, with a count of the number of times each topic was present
- if not too unique, the number of times each topic was present for each ad/campaign

This will allow the advertiser to understand the value of each topic or at least topics that are common for people who later convert on their site.

**Comment by jkarlin** [comment]
Perhaps something like that is possible. Though I worry about all of the various things advertisers will want to pack into conversion reports. Perhaps this might be achievable with [Shared Storage](https://github.com/pythagoraskitty/shared-storage) and a more general form of aggregate reporting?

**Comment by jkarlin** [comment]
I do think that [Shared Storage](https://github.com/WICG/shared-storage) with [Private Aggregation API](https://github.com/patcg-individual-drafts/private-aggregation-api) is the best way to handle this use case in Chrome.
