### ISSUE TITLE
Fruit example clarification 

### ISSUE THREAD

**Issue by RussStringham** [patcg-individual-drafts/topics#24]
Using your example where the top five topics for the first week are:

Top Topic | Parties That Can Learn About the Topic
-- | --
Apples | T, R, S
Bananas | S
Cantaloupe | T, S
Emblica | S
Grapes | T, R, S

and that the user browses primarily the same (types of) sites in subsequent weeks so that the 5 topics (and parties that can learn about them) are identical for weeks 2 and 3, then is the following correct (ignoring the 5% random topic)?

1. The topic selected for a site in the first week, has a 20% chance of being selected again in the second week and a 4% chance of being selected for weeks 1, 2 and 3. In this case, the array will have a single value.
2. Because S can learn about all topics, they are guaranteed to see topics in their array.  At week three they have a 96% chance of seeing at least 2 values
3. R has a 40% chance of seeing a value (Apples or Grapes) for the first week, a 78.8% chance of seeing applies or grapes in at least one week and a 19.2% chance of seeing both Apples and Grapes by week 3

**Comment by jkarlin** [comment]
Hi Russ. I went over your examples a few days ago but forgot to post a response! If memory served I agreed with your calculations (but was off by .2-.4% on the 78.8% one). I didn't run the 19.2% calculation, but will take your word on that one given that the rest of the assumptions seemed correct.

**Comment by RussStringham** [comment]
Thanks for confirming. I'm not so concerned about the exact percentages, but rather just wanted to confirm that I was interpreting correctly the way it should work.

**Comment by nikhiljha95** [comment]
Hi @RussStringham, that's a very interesting calculation. Is there any chance you can detail the calculation you made? In particular:

> Because S can learn about all topics, they are guaranteed to see topics in their array. At week three they have a 96% chance of seeing at least 2 values

This calculation refers to a single site that is served by S, correct?

> R has a 40% chance of seeing a value (Apples or Grapes) for the first week, a 78.8% chance of seeing applies or grapes in at least one week and a 19.2% chance of seeing both Apples and Grapes by week 3

I simply can't wrap my head around the 78.8% and 19.2%. Could you give some hint?

**Comment by martinthomson** [comment]
$1-(1-p)^n$ for $p=0.4$ and $n=3$ is $0.784$, which is the opposite of the probability of getting neither.

I got 21.6% for the other.  That is, the odds of Apple in week $n$ ($p=0.2$) times the odds of Grape in the other $n-1$ weeks ($1-(1-p)^(n-1)$) times $n$.
