### ISSUE TITLE
API for browser extensions?

### ISSUE THREAD

**Issue by dmarti** [patcg-individual-drafts/topics#25]
As a browser user, I might choose to install an extension that will

 * add a topic to my top 5 topics
 * remove a topic from my local topic information store, if that topic is present (otherwise do nothing)
 
It looks like the extension API should prevent extensions from seeing the user's topics or deducing any information about them, to limit incentives to submit malicious extensions.

Related: https://github.com/patcg-individual-drafts/topics/issues/78

**Comment by dmarti** [comment]
Preferred by who? Why enable users to filter topics passed by one method but not another?

**Comment by jkarlin** [comment]
It's not that we're "enabling" it in the javascript case, it's that javascript isn't 100% trustworthy when there are extensions involved.

**Comment by dmarti** [comment]
A user would want to be able to use a trusted extension to filter topics (as they can do with cookie manager extensions), but would not want an untrusted extension to modify topics to track them.

But an untrusted extension could modify other headers to conceal a tracking identifier, so just preventing extensions from modifying topics doesn't seem like it provides any extra protection.
