### ISSUE TITLE
Topics HTTP Header

### ISSUE THREAD

**Issue by luca1x** [patcg-individual-drafts/topics#280]
Hi there, looking at your specification, the following example for a Sec-Browsing-Topics header can be found:
`Sec-Browsing-Topics: (325);v=chrome.1:1:1, ();p=P000000000`

However, in https://developer.chrome.com/en/docs/privacy-sandbox/topics/demo/, an example header is given as 
`Sec-Browsing-Topics: 186;version="chrome.1:1:2206021246";config_version="chrome.1";model_version="2206021246";taxonomy_version="1", 265;version="chrome.1:1:2206021246";config_version="chrome.1";model_version="2206021246";taxonomy_version="1"`

I assume the first one is correct and the second one outdated, as they are clearly not the same format? 
Thanks!

**Comment by xyaoinum** [comment]
Hi @luca1x,

You are right. The first example from the specification is correct. The demo page needs to be updated. (@samdutton).

Can you clarify what do you mean by _"deduce a mapping from browser version to taxonomy version"_? The taxonomy version is part of the version sent in the header (i.e. the `chrome.1:1:1` part), and according to the [specification](https://patcg-individual-drafts.github.io/topics/#browsing-topics-types-version), the version is the result of concatenating « configurationVersion, taxonomyVersion, modelVersion » using ":".
