### ISSUE TITLE
Topics-Internals: Scheduled Updates Seem Not to be Working

### ISSUE THREAD

**Issue by abubakaraziz** [patcg-individual-drafts/topics#300]
Hi,

In my chrome://topics-internals/, the next scheduled calculation time for Topics is 3/29/2024, 11:01:11 PM. However, I don't see the latest epoch calculated even though that date has passed. In all my previous epoch calculations, epochs were calculated after I pressed the Calculate Now button. 

* Do we have to press the Calculate Now button to display the latest epoch on chrome://topics-internals/? Shouldn't the topics-internal page update automatically?

<img width="1805" alt="Screenshot 2024-04-01 at 1 57 51 PM" src="https://github.com/patcg-individual-drafts/topics/assets/10674679/8183363e-e7de-4762-95e8-e88c5030352e">

**Comment by jkarlin** [comment]
Thanks for the report. Seems strange, and I've heard of another similar incident. Will investigate and report back.

**Comment by abubakaraziz** [comment]
Thank you for looking into that. I asked some of my friends, and they faced similar issues.

Quick follow-up: Can you confirm if this issue is only limited to chrome://topics-internals/ (UX issue)? For instance, if the internal topics page doesn't show epoch and topics calculation, will topics still be calculated internally in browser on schedule, and third parties continue to see the topics when they call the API?

**Comment by abubakaraziz** [comment]
@jkarlin just checking out to see if you've any updates regarding this issue? Thank you!

**Comment by jkarlin** [comment]
Still exploring. We have reason to believe that it isn't just UX and are looking for local reproductions to help us debug.

**Comment by jkarlin** [comment]
Okay, sorry for taking so long to get back to this. There is a subtle bug here that @xyaoinum discovered. Long story short, the 1 week timer doesn't increment when a computer is sleeping. So, if it's sleeping a lot, then the 1 recalculation will happen beyond 1 week if the browser hasn't restarted during that time. It's being fixed now.
