### ISSUE TITLE
Redirects and Topics calculation

### ISSUE THREAD

**Issue by chrisn** [patcg-individual-drafts/topics#311]
If I have a hostname `news.bbc.co.uk` that is a 301 permanent redirect to `bbc.co.uk/news`, would the `news.bbc.co.uk` hostname be used in Topics calculation if the user browses to it? Reading the spec, I see that Topics calculation input data needs a Document, which AIUI the browser's initial request to `news.bbc.co.uk` wouldn't have, so wouldn't be included. Have I understood correctly?

(This question was prompted by reading the latest [CMA report](https://assets.publishing.service.gov.uk/media/662baa3efee48e2ee6b81eb1/1._CMA_Q1_2024_update_report_on_Google_Privacy_Sandbox_commitments.pdf) which uses `news.bbc.co.uk` as an example of Topics calculation.)

**Comment by jkarlin** [comment]
You're correct. The hostname used on the page for Topics calculation is the one associated with the loaded document, which is the hostname at the end of the redirect chain. In this case, `bbc.co.uk` is what would be used for Topics calls on the page.

**Comment by chrisn** [comment]
Thank you for confirming, I appreciate your help!
