### ISSUE TITLE
 "high utility" bucket released ?

### ISSUE THREAD

**Issue by nicshub** [patcg-individual-drafts/topics#313]
Hi there,
according to https://developers.google.com/privacy-sandbox/blog/topics-enhancements the Top topics selection using utility bucket was supposed to be delivered in Q4 2023.
Can anyone confirm that is live ?
If so I think that both explainer 
https://github.com/patcg-individual-drafts/topics
and specs should indicate it
https://patcg-individual-drafts.github.io/topics/#derive-top-5-topics-header
Thanks
Salvo

**Comment by jkarlin** [comment]
Sorry, I missed this. Yes it's been live for some time now. Good catch on the spec change, @xyaoinum PTAL.

**Comment by xyaoinum** [comment]
Note that the explainer already indicated this: "... Topics are sorted by a two-level sort – first by priority level and then by visit count ..."

I've updated the spec to indicate this as well: https://github.com/patcg-individual-drafts/topics/pull/315.
