### ISSUE TITLE
Topics for Callers for Web Topics API

### ISSUE THREAD

**Issue by relevance-api-topics** [patcg-individual-drafts/topics#317]
When getting 'top 5 topics', would we count frequency of websites visits based on each eligible caller, or always count based on the browser's whole visiting histories? Thanks.

**Comment by xyaoinum** [comment]
It's based on the frequency of a _subset_ of browsing histories. A browsing history entry (a page) is eligible to participate only if the page had at least one topics caller. See when [topics history storage](https://patcg-individual-drafts.github.io/topics/#user-agent-topics-history-storage) get populated in the spec.

**Comment by relevance-api-topics** [comment]
@xyaoinum thanks for the reply. based on the subset of the browsing histories, do you further rank topics for each caller separately?

ask this based on the understanding that different callers have different 'rights' for topics, only when callers observe the topics, they can receive 1 randomly selected from the top 5.

the 'top 5' are generated within one epoch for all the callers?

**Comment by xyaoinum** [comment]
The ranking depends on the frequency, and also on a a binary priority level (see the [announcement](https://developers.google.com/privacy-sandbox/blog/topics-enhancements), [topics-utility-buckets-v1.md](https://github.com/patcg-individual-drafts/topics/blob/main/topics-utility-buckets-v1.md), [pending spec update](https://github.com/patcg-individual-drafts/topics/pull/315)). However, it does not depend on the frequency of callers.

But note that it doesn't mean all the callers can observer all top 5 topics. Per the explainer: "Only callers that observed the user visit a site about the topic in question within the past three weeks can receive the topic." The browser does need to track which caller observed which top 5 topics (corresponding to the [top 5 topics with caller domains](https://patcg-individual-drafts.github.io/topics#epoch-top-5-topics-with-caller-domains) in the spec).

**Comment by xyaoinum** [comment]
@relevance-api-topics Your first statement is accurate

**Comment by relevance-api-topics** [comment]
Hi @xyaoinum, thanks for your information and help! Hope to ask a follow-up question: from your side, do you have a general understanding that what's the percentage of visiting history is in-scope for Topics API, near 100%? thanks!

**Comment by relevance-api-topics** [comment]
Hi @xyaoinum, thanks for your information again, hope to re-open this case also with another quick follow-up question, for 'a 'page' is in-scope as long as one caller observe it':

- if an page visit happened before the first observer observe it, is this visit contributing to the epoch's ranking?
- if an page is observed by one caller, but the caller doesn't want to do fetch call every time the page is visited, will all page visits contribute to ranking, or only the visits having fetch observation call?

Thanks!

**Comment by xyaoinum** [comment]
Hi @relevance-api-topics:

>  from your side, do you have a general understanding that what's the percentage of visiting history is in-scope for Topics API, near 100%?

It's actually a small percentage. Based on https://chromestatus.com/metrics/feature/timeline/popularity/5102, about 5% page visits has Topics calls (in any form; and whether observe or not). Note that the measurement is quite new and might not fully stabilize until M131 reaches Stable on 12/03. But it should be clear that the in-scope history is far from 100%.

> if an page visit happened before the first observer observe it, is this visit contributing to the epoch's ranking?

I'm not sure what you mean. A page visit always happens before the first observer observes it. Any observation during the page's life cycle will make the page eligible for topics.

> if an page is observed by one caller, but the caller doesn't want to do fetch call every time the page is visited, will all page visits contribute to the Epoch topic ranking, or only the page visits having fetch observation calls can contribute?

only the page visits having observation calls can contribute.
