### ISSUE TITLE
Why would FLoC interest-cohort browser policy block Topics API?

### ISSUE THREAD

**Issue by relevance-api-topics** [patcg-individual-drafts/topics#318]
Looks like browser interest-cohort setting could block Topics API, is this as expected? Thanks.

**Comment by xyaoinum** [comment]
Yes this is expected. Topics API is an [evolution from FLoC](https://github.com/patcg-individual-drafts/topics?tab=readme-ov-file#evolution-from-floc). It honors FLoC's permissions policy. (Per the explainer: _"Note: The old Permissions-Policy: interest-cohort=() from FLoC will also forbid topic calculation."_)
