### ISSUE TITLE
Does every eTLD+1 visiting website need enrollment/attestation?

### ISSUE THREAD

**Issue by relevance-api-topics** [patcg-individual-drafts/topics#324]
Hope to ask a question for enrollment/attestation requirement for utilizing Topics API- 

Support a browser has visiting history for hostname1.com, hostname2.com, both websites do fetch call to service.com through client JS tool offered by service.com, do hostname1.com and hostname2.com need enrollment/attestation firstly to successfully do fetch call to service.com with Topics?

Please help let us know. Thanks!

**Comment by michaelkleber** [comment]
1. In the situation you describe, it should be service.com that enrolls — they are the one interacting with the API, through HTTP headers on requests going to their server.
2. For future questions like this I would recommend instead the Privacy Sandbox Developer Support repository, https://github.com/privacysandbox/privacy-sandbox-dev-support
