### ISSUE TITLE
Topics API - feature overrides based on etld+1 ?

### ISSUE THREAD

**Issue by relevance-api-topics** [patcg-individual-drafts/topics#326]
Hi experts, we are having trouble to fetching topics for the below case:

- observe topic via fetch call to server1.region.test.com, chrome://topics-internals/ has test.com recognized the observer.
- however, when document.browsingTopics() on server1.region.test.com, nothing obtained.
- only when adding server1.region.test.com to chrome://flags/#privacy-sandbox-enrollment-overrides, topic can be fetched.
- Question: we already added test.com into chrome://flags/#privacy-sandbox-enrollment-overrides, isn't it be used for server1.region.test.com, server2.region.test.com... serverN.region.test.com, directly? Otherwise every server need to override for testing.

Is anything missed from our side, or this is an issue to update? Thanks!

**Comment by xyaoinum** [comment]
Both the observation and the enrollment rely on etld+1.

Adding `test.com` to `chrome://flags/#privacy-sandbox-enrollment-overrides` should be sufficient for your case. Also, calling `fetch('https://server1.region.test.com', {browsingTopics: true})` should produce the same results as calling `document.browsingTopics()` within a frame on `https://server1.region.test.com`.

Are you seeing differences between these two methods, or are neither working as expected? It would be helpful if you could provide detailed reproduction steps. If possible, please consider [filing a bug report](https://issues.chromium.org/u/1/issues/new?component=1456494&template=0).
