### ISSUE TITLE
Inquiry for specifications of updating topic master data

### ISSUE THREAD

**Issue by soyoshidaFB** [patcg-individual-drafts/topics#327]
Hello, 

I'm trying to get topic master data on my application and update it periodically then I'm assuming that I need to take into consideration the addition, update, and delete of topic data like below. Please let me know if my understanding is incorrect, as the following statements are only my assumptions.

・Addition: New topic is added and CriterionID (I referred to https://developers.google.com/google-ads/api/data/verticals) is newly numbered.
・Update: Existing CriterionID will be no changed, but topic's Parent ID or topic's name will be changed.(This is reorganization of categories.)
・Delete: Topic and CriterionID will be logical deletion.

Thank you in advance.

**Comment by xyaoinum** [comment]
The taxonomy update is not specified. This provides browser vendors with flexibility in implementation.

But the heuristics of Chrome's taxonomy update from [V1](https://github.com/patcg-individual-drafts/topics/blob/main/taxonomy_v1.md) to [V2](https://github.com/patcg-individual-drafts/topics/blob/main/taxonomy_v2.md) seem to be consistent with your understanding:

- A single taxonomy tree is maintained for topics from both V1 and V2.
- The same topic ID represents the same meaning.
- The tree only grows – adding new topics or connections, never shrinking.
- However, some topics or links could be "inactive" in a version, which could give the impression of deletion or reorganization.

Examples:
- "Pickup Trucks" now has "Trucks, Vans & SUVs" as an intermediate parent.
- "Foreign Language Study" now has "Education" as a second parent, and its original parent "Reference" becomes inactive.

Impact of "inactive" topics: These topics won't be used for new classification. However, they're still considered when enforcing user blocks: if a user blocked a topic in V1, its children will remain blocked in V2 (even if the child topic appears under a different parent in V2).

**Comment by soyoshidaFB** [comment]
Thank you very much for your useful observations.
If the topic ID represents the same topic, I believe there is little concern in upgrading topic master.
