### ISSUE TITLE
Topics API Taxonomy version through fetch call

### ISSUE THREAD

**Issue by relevance-api-topics** [patcg-individual-drafts/topics#334]
Hi Topics API experts,

When taxonomy has a new version, the topic ids also would change if we understand it correctly, through fetch calls, looks like there is no easy way to access taxonomy version, how do we ensure backward compatibility or do we miss anything? Thanks!

**Comment by xyaoinum** [comment]
The version breakdown is now clarified in the explainer. (commit: https://github.com/patcg-individual-drafts/topics/commit/3cb31f5b6d507044d5e4e83a0407cf18270a14f7)

**Comment by relevance-api-topics** [comment]
thanks @jkarlin, @xyaoinum thanks for the info! quick follow-up question is 'chrome.1' as the configuration, it's chrome.1 meaning there is other choices other than chrome? thanks.

**Comment by xyaoinum** [comment]
@relevance-api-topics Currently, in Chrome, the configuration version always starts with `chrome.`.

**Comment by Dixie5644** [comment]
[]()

**Comment by Dixie5644** [comment]
> 6.

**Comment by Dixie5644** [comment]
- > 6.
