### ISSUE TITLE
Doc for cross week Topics selection

### ISSUE THREAD

**Issue by relevance-api-topics** [patcg-individual-drafts/topics#342]
Hi Topics API experts,

Hope to ask what is the strategy underlying for cross week duplicated topics, is the API picking independently among weeks and then merge? One edge case to do so is only one unique topic is selected among 3 weeks which actually have different top topics. Thanks!

**Comment by jkarlin** [comment]
Each week's (epochs) topics are calculated independently. The particular topic chosen to be returned from each epoch depends on the site the caller is on. We do not take into account that the topic might be repeated across epochs for a given caller (and should therefore consider selecting a different topic). It's something we could consider exploring the effect of.
