### ISSUE TITLE
How to decide if a page is 'topics history entry'

### ISSUE THREAD

**Issue by relevance-api-topics** [patcg-individual-drafts/topics#349]
Hi Topics API experts,

We are not sure if we could understand correctly for how Topics API decide if a page view by an user is regarded as 'topic history entry':

if the same page has 2 user views in one epoch, first page load with one caller with a fetch call for observation, second page load without any caller to observe (e.g. the caller does periodically observations). Will the second page view without observer being regarded as topic history entry and affect topic ranking?

Thanks!

**Comment by xyaoinum** [comment]
To be eligible for the weekly topics calculation, a page visit must have an 'observe' call (can be from any caller). Without an 'observe' call, the visit won't be considered for topic history.

**Comment by relevance-api-topics** [comment]
@xyaoinum I see, thanks for the confirmation!
