### ISSUE TITLE
Question about Chromium involvement

### ISSUE THREAD

**Issue by relevance-api-topics** [patcg-individual-drafts/topics#350]
Hi Topics API experts,

Hope could post here for us missing some information about Chromium:

For Desktop, would Chrome share with other browsers based on Chromium the same observation and ranking context?

For Mobile, would Android Chrome share with other Android browsers based on Chromium / In-App Chromium the same observation and ranking context?

Thanks!

**Comment by jkarlin** [comment]
Hi TC, please update your company/affiliation in your github profile. It's helpful to know who it is we're speaking with.

The Chrome browser does not share its Topics data with other browsers on the device.
