### ISSUE TITLE
Reach issue

### ISSUE THREAD

**Issue by jdelhommeau** [patcg-individual-drafts/topics#37]
Since user can have up to 15 topics computed by the browser, and only 3 are returned on a given site, doesn't that mean that advertisers interested in specific topic will see their reach divided by 5 compared to today's cookie based approach?
For example, a user has the "sport" topic. As per current design, only 1 site out of 5 (on average) will access the "sport" topic from the user.
If an advertiser targets the sport topic, it means it can target that user only on that 1 site that got access to the sport topic.
Isn't it a risk of severely impacting the advertiser's reach?

**Comment by jkarlin** [comment]
You're right that this is significantly less data about the user being conveyed than with third party cookies. We're making an explicit trade-off here to still make it possible to perform interest based advertising, while preserving user privacy by revealing only what is necessary. Hopefully the up-to-three topics are sufficient.

**Comment by jdelhommeau** [comment]
I imagine this will be a KPI to keep in mind during testing, but I really have a hard time imagining that top 3 topics, among 15 topics computed for that user based only on hostname, among the total 350 topics that exist will result in any meaningful reach for advertisers, beyond maybe the top 5 topics that will be represented on the internet.

**Comment by jkarlin** [comment]
We're looking into methods (see https://github.com/patcg-individual-drafts/topics/issues/42)  of weighting the topics so that they're more meaningful. e.g., we could weight them by inverse frequency, so topics that aren't seen often rise to the top.

**Comment by jkarlin** [comment]
Closing in favor of #42
