### ISSUE TITLE
Clarification regarding multiple callers on a site

### ISSUE THREAD

**Issue by lbdvt** [patcg-individual-drafts/topics#43]
The explainer says:

> Whatever topic is returned, will continue to be returned for any caller on that site for the remainder of the three weeks.

Could you please tell if the following example is correct:

- AdTech A and AdTech B are two third-party integrated on Site S
- A user lands on S and both A and B call the Topics API on page load
- Whichever call is resolved first sets the topics to be returned for that week (on that site and for that user)
- Let's say that call made by A is resolved first and topics Banana, Apple, and Grapes are returned. If B is only eligible to get Banana, B's call will only return Banana, and no other B eligible topic that the user might have

**Comment by jkarlin** [comment]
The caller does not influence which of the 5 topics is chosen. So regardless of if A or B call first, the same topic will be returned.

**Comment by lbdvt** [comment]
Thanks, I see, and it indeed fits with https://github.com/jkarlin/topics/issues/24 .

So for each epoch, on a given site and user, the answer to a call is (without taking into account the random topic): 
[the one topic for that user x site x epoch, randomly chosen among the top five topics for that user x epoch and then fixed for that site] intersect [caller's eligible topics]

Correct?
