### ISSUE TITLE
Objectives in terms of protection against cross-site user identification

### ISSUE THREAD

**Issue by lbdvt** [patcg-individual-drafts/topics#47]
The explainer sets as first privacy goal (https://github.com/jkarlin/topics#privacy-goals):

> It must be difficult to reidentify significant numbers of users across sites using just the API.

What are the values (orders of magnitude) that Google would put behind "difficult" and "significant numbers of users"?

**Comment by jkarlin** [comment]
The time it takes to reidentify users is going to depend on the site. Two sites with few users will be able to reidentify users faster, than sites with lots of users. I don't have hard numbers here, as it's all a balancing act. I think ideally it would take > 5 weeks on average to reidentify a user across two sites, but again, that's really going to depend on the particular sites.
