### ISSUE TITLE
What is the performance impact?

### ISSUE THREAD

**Issue by AramZS** [patcg-individual-drafts/topics#51]
This topic came up in the Web-Adv W3C group and I do not see a issue addressing it here? What is the performance impact of this system in terms of delaying time to first ad call if the ad system is dependent on calling this API?

**Comment by jkarlin** [comment]
Good question. This has been raised in https://github.com/patcg-individual-drafts/topics/issues/7 as well. Basically, opening a cross-site iframe just to run a single javascript call and postMessage it to wherever it needs to go can be expensive. That is one of the major motivators for adding header support to the API, which we plan to add. Closing this and keeping #7.
