### ISSUE TITLE
How about just ... not

### ISSUE THREAD

**Issue by Gunni** [patcg-individual-drafts/topics#58]
> With the upcoming removal of third-party cookies on the web, key use cases that browsers want to support will need to be addressed with new APIs. One of those use cases is interest-based advertising.

Have you considered just ... not supporting that use case.

Pretty much all users are against tracking.
Those that are not, are simply unaware of how it works, and when explained to them they are against it.

There is a lot of laws in recent years because tracking is too ubiquitous (GDPR, CCPA, et al).

Anyone asking for any kind of tracking does so only because they profit from it (directly or indirectly).

**Comment by jkarlin** [comment]
The purpose of this repository is to explore ways in which we can support interest based advertising in a way that's significantly more private than today's practices. Please keep comments on-topic.

**Comment by dmarti** [comment]
@gunni General discussions of the overall advantages/disadvantages of a particular proposal can be brought to the [Private Advertising Technology Community Group](https://patcg.github.io/) (PATCG).

 * [Issues on the patcg/meetings repository](https://github.com/patcg/meetings/issues)
 
 * Post to the [public-patcg@w3.org mailing list](https://lists.w3.org/Archives/Public/public-patcg/).

PATCG is a community group that anyone may join, free of charge.  As a W3C Community Group, all work and communication within PATCG is covered by the [W3C Code of Ethics and Professional Conduct](https://www.w3.org/Consortium/cepc/). (The group could use more representation from greater variety of web stakeholders. and more participation from people who make and use independent web sites would be welcome.)

**Comment by michaelkleber** [comment]
Unfortunately, the best information we have is that most web sites lose somewhere between 50% and 70% of their ad if the only advertising is contextual.  See e.g. https://twitter.com/garjoh_canuck/status/1318989360407236609.  Moreover, news sites are hit much harder than other types of websites.  So this proposal, and this CG, are working on alternatives to the Thanos Snap outcome for the web.
