### ISSUE TITLE
Should sites receive historic topics every visit, or first visit only?

### ISSUE THREAD

**Issue by jkarlin** [patcg-individual-drafts/topics#6]
* For sites that users frequently visit there is no difference in privacy. For infrequently visited sites, this becomes a trade-off between topic dissemination rate and utility.
* How might one define “first visit”? 
  * It could be: does the site have any cookies or other storage for the user? If so, it’s not first visit.

**Comment by igrigorik** [comment]
Providing information on "first visit only" doesn't change the dissemination rate...? My understanding is that the question is whether there should be some bar beyond "user loaded page" that gates access to topics — correct?

My hunch is that the browser _should_ reserve the ability to modify the list of returned topics not only based on the caller, but also based on the context of site and visit. For example, if a hostname is flagged by Safe Browsing, I would expect the API to return an empty set, ditto for Incognito-loaded visit. Other heuristics could be integrated over time as well.. e.g. referrer quality / source, and so on.

**Comment by jkarlin** [comment]
Closing as this hasn't really come back up. Can revisit in the future.

**Comment by chromeprivetlimited** [comment]
a116e9e404dd96c7793fe6542c53e9a9d93cb75b

**Comment by rodriguezdanielleor-spec** [comment]
- [ ] main
