### ISSUE TITLE
Final API for JSON returned by document.browsingTopics

### ISSUE THREAD

**Issue by fhoering** [patcg-individual-drafts/topics#62]
Currently the docs says that the returned JSON looks like this:
```
// document.browsingTopics() returns an array of up to three topic objects in random order.
const topics = await document.browsingTopics();

// The returned array looks like: [{'value': Number, 'taxonomyVersion': String, 'modelVersion': String}]
```

In Chrome is has been implemented this way:
https://github.com/chromium/chromium/blob/9d67870b45546a797fd7286d2bcc4ae8396499d1/chrome/browser/browsing_topics/browsing_topics_service_browsertest.cc#L59
https://github.com/chromium/chromium/commit/cc37939dc5f9987a6d649d5357627f85ad9f1e03

```
[{"configVersion":"chrome.1","modelVersion":"2","taxonomyVersion":"1","topic":1,"version":"chrome.1:1:2"}]
```

Is this the final version that will be used for the Topics Origin Trial ? Is is important to know the final structure for the parsing the JSON.

**Comment by jkarlin** [comment]
Yes, go with the implementation. I will update the explainer to reflect that.

**Comment by fhoering** [comment]
@jkarlin 
Ok. Thanks. 
One additional question. Why not at least factorizing all the version parameters across the topics object ?
It looks like very redundant information that might change but not inside one API call I suppose.

Something like this:

```
{
 "configVersion":"chrome.1","modelVersion":"2","taxonomyVersion":"1","version":"chrome.1:1:2";
 "topics": [1,2,3]
}
```

instead of:
```
[
 {"configVersion":"chrome.1","modelVersion":"2","taxonomyVersion":"1","topic":**1**,"version":"chrome.1:1:2"},
{"configVersion":"chrome.1","modelVersion":"2","taxonomyVersion":"1","topic":**2**, "version":"chrome.1:1:2"},
{"configVersion":"chrome.1","modelVersion":"2","taxonomyVersion":"1","topic":**3**,"version":"chrome.1:1:2"}
]
```

**Comment by jkarlin** [comment]
Each topic is part of an epoch (week of time). So a topic generated two weeks ago might have a different set of versions than one from this week.

**Comment by fhoering** [comment]
Ok. We will go with the current implementation. Thanks for the explanation

**Comment by jkarlin** [comment]
Happy to, but can you ask in a new issue as it's unrelated to this closed thread.
