### ISSUE TITLE
Definition of fields in the JSON returned by the TOPICS API

### ISSUE THREAD

**Issue by arouzaud** [patcg-individual-drafts/topics#63]
Hello,
In the current implementation of TOPICS, the JSON returned by _document.browsingTopics_ looks like: 

`[{"configVersion":"chrome.1","modelVersion":"2","taxonomyVersion":"1","topic":1,"version":"chrome.1:1:2"}]`

1. What's the definition of _configVersion_ and _version_ fields, as they were not included in the original spec?
2. Do you plan to experiment several models and taxonomies during the OT?

**Comment by jkarlin** [comment]
Thanks for creating the issue.

> What's the definition of configVersion and version fields, as they were not included in the original spec?

configVersion: Basically this will change when Chrome changes parameters (e.g., number of topics per epoch, duration of epoch) or how it chooses the top topics.

modelVersion: The version of the model used to map urls to topics.

taxonomyVersion: The version of the topics taxonomy used by the API

> Do you plan to experiment several models and taxonomies during the OT?

We don't have any current plans to, but that's not to say that it won't happen.

**Comment by arouzaud** [comment]
Ok thanks @jkarlin for the prompt answer.
Btw, do you have a page providing some details about the model used to generate topics, a bit like this page for FLoC?
https://www.chromium.org/Home/chromium-privacy/privacy-sandbox/floc/

**Comment by jkarlin** [comment]
> Btw, do you have a page providing some details about the model used to generate topics, a bit like this page for FLoC?

Not yet, but it's a good idea to create one.

> Can you confirm the version field format won't change during the OT, i.e. be a concatenation of configVersion, taxonomyVersion and modelVersion, as coded below?

It will continue to be a concatenation of those three versions. Those underlying versions _may_ change during the OT.

Note that I can't say with absolute certainty what will/won't change so early in the OT. Part of the purpose of the OT is to get developer feedback and evolve the API. But we do not have any plans to change the behavior of the version field.
