### ISSUE TITLE
Classifier timeline and white paper

### ISSUE THREAD

**Issue by fmingyan** [patcg-individual-drafts/topics#64]
Could you provide some guidance on when the classifier weights will become public? Will there be a white paper on the classifier similar to what was published for FLoC?

**Comment by fmingyan** [comment]
Thank you, could you also guide on where to find the top 10k domains currently used and how it can be mapped to model input?

**Comment by leeronisrael** [comment]
You can find the path to the model file in the "Classifier" tab of chrome://topics-internals/ page (see docs [here](https://developer.chrome.com/docs/privacy-sandbox/topics/#debug)). The top 10k domains currently used are in the override_list.pb.gz file found in the same directory as the model above. The domain to topics associations in the list are utilized by the API in lieu of the output of the model itself.

To run the model directly, refer to documentation here: https://www.tensorflow.org/lite/guide/inference#running_a_model (Also see: https://www.tensorflow.org/learn)

To inspect the override_list.pb.gz file:

Unpack it: gunzip -c override_list.pb.gz > override_list.pb
Use protoc to inspect: protoc --decode_raw < override_list.pb > output.txt
Also see: Taxonomy of topics with IDs: https://github.com/patcg-individual-drafts/topics/blob/main/taxonomy_v1.md
