### ISSUE TITLE
How often will modelVersion and taxonomyVersion change during the origin trial?

### ISSUE THREAD

**Issue by timphsieh** [patcg-individual-drafts/topics#66]
Will the modelVersion and taxonomyVersion change:
  - Often  (e.g. once per week)
  - Occasionally (e.g. once per month)
  - Rarely (e.g. once per 3 months)
  - Will not change during the origin trial.

The motivation for the question is to understand how often will document.browsingTopics() return multiple topics with different modelVersion and taxnomyVersion.

**Comment by jkarlin** [comment]
The expectation is for taxonomy changes to be rare by your definition. I'm less certain about model changes. I do expect some updates there, but during the OT likely once per month or so at most.

**Comment by jkarlin** [comment]
We haven't yet thought through exactly what the details of a taxonomy change would be yet, as we haven't yet had to implement one. That said, the hope is that it would not invalidate old epochs. Each epoch would have topics with their own taxonomy version.
