### ISSUE TITLE
Unable to get Topics values during origin trail

### ISSUE THREAD

**Issue by boazyaniv** [patcg-individual-drafts/topics#68]
I downloaded the latest chrome beta, activated all flags as describe in:
https://developer.chrome.com/docs/privacy-sandbox/topics/ --> Test with chrome://flags or feature flags

I am surfing through different websites for the last week but still getting empty array from the JS api: 
document.browsingTopics()

We are unable to do proper testing without getting an actual values, 
please advise

**Comment by bershanskiy** [comment]
I'm looking for a way to test Topics API, and I would like to stuff my browser profiles with different histories to compare how the resulting topics differ. Is there a simple way to do this? Specifically, I'm interested in testing the effectiveness of the "plausible deniability" rule to lie in 5% of cases, so I'd like to be able to create testing profiles easily.

**Comment by ydennisy** [comment]
hi @jkarlin 

I am having a similar problem wherein the API consistently returns `[]`.

I have a js script deployed across multiple domains, which inserts the origin trial key, checks for support of topics and then calls the API, support is very low out of millions of loads about 50 have support, but within all the supported calls not a single one has returned anything but an empty array.

Your help would be greatly appreciated!

**Comment by jkarlin** [comment]
@ydennisy The Topics API was disabled while we sorted out a bug. It's reenabled now but has only resumed running for a few days (since Monday the 22nd). It takes a week between epoch calculations. So at this point you shouldn't be seeing any topics.

@bershanskiy We're planning to add a button to chrome://topics-internals that would allow you to 'calculate now' rather than wait for the browser to calculate at the next epoch change. This would allow you to browse around for a bit, then hit the button, and see what the resulting topics are. Would that help?

**Comment by ydennisy** [comment]
@jkarlin thank you very much for your reply - I was scratching my head a lot, and could soon have developed a bald spot :)

**Comment by ydennisy** [comment]
Hey @jkarlin 

There still seems to be some issues with this feature, I can now occasinally see a non empty array, but the internals are always:

```
[{ "value": null, "taxonomy_version": "1", "classifier_version": null }]
```

Some users will have multiple such entries.

There is no error being thrown when such a result appears. Are there still issues with this API?

**Comment by xyaoinum** [comment]
Hi @ydennisy 
I'm not sure how invalid topics can be returned; the [code](https://source.chromium.org/chromium/chromium/src/+/main:components/browsing_topics/browsing_topics_service_impl.cc?q=%22Only%20add%20a%20non-empty%20topic%20to%20the%20result%22) should have prevented it. Do you happen to have the original array that has the [BrowsingTopic](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/browsing_topics/browsing_topic.idl) dictionary entries? (It should have 5 fields: topic, version, configVersion, modelVersion, taxonomyVersion)

**Comment by samdutton** [comment]
Apologies for the outdated documentation — I've made an update here: [PR](https://github.com/GoogleChrome/developer.chrome.com/pull/3139) 

@xyaoinum — a more detailed explanation for `configVersion` (and any other clarifications/improvements) welcome.

**Comment by samdutton** [comment]
The update to the [article](https://developer.chrome.com/docs/privacy-sandbox/topics/#how-does-the-topics-api-work) has now been published.
